<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Abhilash" name="Load Exposure - CSV" tests="1" failures="1" timestamp="23 Jul 2015 05:32:56 GMT" time="98.802" errors="0">
  <testcase name="loadExposure_CSV" time="83.249" classname="com.eigenRisk.TestSuite.Exposure_Load">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at com.eigenRisk.TestSuite.Exposure_Load.loadExposure_CSV(Exposure_Load.java:135)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- loadExposure_CSV -->
</testsuite> <!-- Load Exposure - CSV -->
